#!/usr/bin/env node
//
// sync-ignores.mjs — regenerate every secret-exclusion file in this repo from
// the single master list at .github/scripts/secret-patterns.txt.
//
// Usage:
//   node .github/scripts/sync-ignores.mjs           # rewrite all targets
//   node .github/scripts/sync-ignores.mjs --check   # CI mode: exit 1 on drift
//
// Why: each coding assistant uses a different ignore mechanism (gitignore-style
// files, Claude Code's permissions.deny JSON, Copilot's content-exclusion YAML).
// Hand-syncing N files is how rules drift and weaken. One list, one script.
/* eslint-disable  security/detect-non-literal-fs-filename */
/* eslint-disable  no-console */
import fs from "node:fs";
import readline from "node:readline";

const PATTERNS_FILE = ".github/scripts/secret-patterns.txt";

const OPENING_COMMENT_LINE =
  "# === BEGIN SECURITY FLOOR (generated by sync-ignores.mjs — do not edit) ===";
const CLOSING_COMMENT_LINE = "# === END SECURITY FLOOR ===";

const GITIGNORE_TARGETS = [
  ".gitignore",
  ".cursorignore",
  ".claudeignore",
  ".geminiignore",
  ".aiexclude",
  ".clineignore",
  ".codeiumignore",
];

const COPILOT_TARGET = "docs/security/copilot-content-exclusion.yml";
const CLAUDE_TARGET = ".claude/settings.json";

async function readPatterns() {
  const fileStream = fs.createReadStream(PATTERNS_FILE);
  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity,
  });
  const patterns = [];
  for await (const line of rl) {
    if (line.trim() && !line.trim().startsWith("#")) {
      patterns.push(line.trim());
    }
  }
  return patterns;
}

function replaceMarkerBlock(content, newBlockLines, filePath) {
  const lines = content.split("\n");
  let beginIdx = -1;
  let endIdx = -1;
  for (let [index, line] of lines.entries()) {
    if (beginIdx === -1 && line.trim() === OPENING_COMMENT_LINE) {
      beginIdx = index;
    } else if (beginIdx !== -1 && line.trim() === CLOSING_COMMENT_LINE) {
      endIdx = index;
      break;
    }
  }
  if (beginIdx === -1 || endIdx === -1) {
    throw new Error(
      `${filePath}: managed marker block not found ` +
        `(expected lines "${OPENING_COMMENT_LINE}" and "${CLOSING_COMMENT_LINE}")`,
    );
  }
  const before = lines.slice(0, beginIdx);
  const after = lines.slice(endIdx + 1);
  return [...before, ...newBlockLines, ...after].join("\n");
}

function renderGitignoreBlock(patterns) {
  return [OPENING_COMMENT_LINE, ...patterns, CLOSING_COMMENT_LINE];
}

function copilotTransform(pattern) {
  const negated = pattern.startsWith("!");
  const body = negated ? pattern.slice(1) : pattern;
  const glob = body.endsWith("/") ? `**/${body}**` : `**/${body}`;
  return negated ? `!${glob}` : glob;
}

function renderCopilotBlock(patterns) {
  const items = patterns.map((p) => `  - "${copilotTransform(p)}"`);
  return [`  ${OPENING_COMMENT_LINE}`, ...items, `  ${CLOSING_COMMENT_LINE}`];
}

function toClaudeDenyRules(patterns) {
  const rules = [];
  for (const p of patterns) {
    if (p.startsWith("!")) {
      continue; // eslint-disable-line no-continue
    }
    if (p.endsWith("/")) {
      rules.push(`Read(${p}**)`, `Read(**/${p}**)`);
    } else {
      rules.push(`Read(**/${p})`);
    }
  }
  return rules;
}

function regenerateGitignoreStyle(filePath, patterns) {
  const content = fs.readFileSync(filePath, "utf8");
  return replaceMarkerBlock(content, renderGitignoreBlock(patterns), filePath);
}

function regenerateCopilot(filePath, patterns) {
  const content = fs.readFileSync(filePath, "utf8");
  return replaceMarkerBlock(content, renderCopilotBlock(patterns), filePath);
}

async function regenerateClaudeSettings(filePath, patterns) {
  const cfg = JSON.parse(await fs.promises.readFile(filePath, "utf8"));
  cfg.permissions = cfg.permissions || {};
  const floor = toClaudeDenyRules(patterns);
  const floorSet = new Set(floor);
  const existing = Array.isArray(cfg.permissions.deny)
    ? cfg.permissions.deny
    : [];
  const extras = existing.filter((r) => !floorSet.has(r));
  cfg.permissions.deny = [...floor, ...extras];
  return JSON.stringify(cfg, null, 2) + "\n"; // eslint-disable-line prefer-template
}

async function checkClaudeSettings(filePath, patterns) {
  const deny = JSON.parse(await fs.promises.readFile(filePath, "utf8"))
    ?.permissions?.deny;
  const denySet = new Set(Array.isArray(deny) ? deny : []);
  const missing = toClaudeDenyRules(patterns).filter((r) => !denySet.has(r));
  return missing.length > 0
    ? `${filePath}: missing required deny rules: ${missing.join(", ")}`
    : null;
}

const TARGETS = [
  ...GITIGNORE_TARGETS.map((filePath) => ({
    filePath,
    regenerate: regenerateGitignoreStyle,
  })),
  { filePath: COPILOT_TARGET, regenerate: regenerateCopilot },
  {
    filePath: CLAUDE_TARGET,
    regenerate: regenerateClaudeSettings,
    check: checkClaudeSettings,
  },
];

function reportFailures(failures, checkMode) {
  const header = checkMode
    ? "Security-floor check FAILED:"
    : "sync-ignores FAILED:";
  console.error(`${header}\n`);
  for (const f of failures) {
    console.error(`  ✗ ${f}`);
  }
  if (checkMode) {
    console.error(
      `\nRun \`node .github/scripts/sync-ignores.mjs\` to regenerate, then commit the result.`,
    );
  }
  console.error(
    "\nThese rules keep secrets out of coding assistants and version control.",
  );
  console.error(
    "Changes to the security floor need security-team review (see CODEOWNERS).",
  );
}

async function _checkTarget({ filePath, regenerate, check }, patterns) {
  if (check) {
    return check(filePath, patterns);
  }
  const current = fs.readFileSync(filePath, "utf8");
  return current === (await regenerate(filePath, patterns))
    ? null
    : `${filePath}: out of sync with ${PATTERNS_FILE}`;
}

async function syncTarget({ filePath, regenerate }, patterns) {
  fs.writeFileSync(filePath, await regenerate(filePath, patterns));
}

async function main() {
  const checkMode = process.argv.includes("--check");
  const patterns = await readPatterns();
  const failures = [];

  for (const target of TARGETS) {
    if (!fs.existsSync(target.filePath)) {
      failures.push(
        `${target.filePath}: missing entirely (security floor file removed)`,
      );
      continue; // eslint-disable-line no-continue
    }
    try {
      if (checkMode) {
        const problem = await _checkTarget(target, patterns);
        if (problem) {
          failures.push(problem);
        }
      } else {
        await syncTarget(target, patterns);
      }
    } catch (error) {
      failures.push(error.message);
    }
  }

  if (failures.length > 0) {
    reportFailures(failures, checkMode);
    process.exit(1);
  }

  const successMsg = checkMode
    ? `Security-floor check passed — all targets match ${PATTERNS_FILE}.`
    : `Updated ${TARGETS.length} files from ${PATTERNS_FILE}.`;
  console.log(successMsg);
}

try {
  await main();
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
