name: All CI tasks

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-all-jobs:
    name: All CI tasks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use NVM node version
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn format

      - name: Run type check
        run: yarn typecheck
